import { FLOW_RUNNING_STATUS, FLOW_DEPLOY_STATUS, FLOW_ONLINE_STATUS } from './index';


const STATUS_COLOR_MAP = {
  [FLOW_DEPLOY_STATUS.UNDEPLOY]: '#ff9800',
  [FLOW_DEPLOY_STATUS.DEPLOYING]: '#2196f3',
  [FLOW_DEPLOY_STATUS.SUCCESS]: '#4caf50',
  [FLOW_DEPLOY_STATUS.FAILED]: '#f44336',
  [FLOW_RUNNING_STATUS.UNUSED]: '#808fad',
  [FLOW_RUNNING_STATUS.RUNNING]: '#4caf50',
  [FLOW_RUNNING_STATUS.EXCETION]: '#ccc',
  [FLOW_RUNNING_STATUS.STOPING]: '#2196f3',
  [FLOW_ONLINE_STATUS.ONLINE]: '#4caf50',
  [FLOW_ONLINE_STATUS.OFFLINE]: '#ff9800',
};


export default {
  STATUS_COLOR_MAP
};
